### ISSUE TITLE
Possible to call normal commands in switch definition?

### ISSUE THREAD

**Issue by sevensidedmarble** [AndrewRadev/switch.vim#78]
I want to write a switch for transforming base64 text, but to do this I need to call out to the `!` command, obviously, to call a shell function. How would you do something like that with this plugin?

**Comment by AndrewRadev** [comment]
Right now, there's no way to do what you need, although I've been considering something like that for a long time. Maybe a `normal!` command executed, or, in your case, a `!` or `system`-invoked command.

There are certain existing "modifiers" to definitions that might provide an example about how the interface might look. Here's the examples:

``` vim
let g:switch_custom_definitions =
    \ [
    \   switch#NormalizedCase(['one', 'two']),
    \   switch#Words(['three', 'four']),
    \   switch#NormalizedCaseWords(['five', 'six']),
    \ ]
```

So, `NormalizedCase`, for example, just takes the input definitions and generates ones for `One`/`Two` and `ONE`/`TWO`.

What do you think about something like this:

``` vim
let g:switch_custom_definitions = [
      \   switch#SystemCall({
      \     'data:text/plain,\zs.*'        => 'echo "\0" | base64 -'
      \     'data:text/plain;base64,\zs.*' => 'echo "\0" | base64 -d -'
      \   })
      \ ]
```

So, the key would be the pattern to match under the cursor, and the value would be the external command to invoke, with `\0` being the match, `\1` the first submatch, etc. Which would mean that the above might be a switch between base64-encoded and non-encoded version of a data-url, maybe (though I have no idea if it would work in context).

In this particular case, it would actually be easier for the match to be the *input* of the command -- maybe it would be more sensible to provide the match as an input instead, so:

``` vim
let g:switch_custom_definitions = [
      \   switch#SystemCall({
      \     'data:text/plain,\zs.*'        => 'base64 -'
      \     'data:text/plain;base64,\zs.*' => 'base64 -d -'
      \   })
      \ ]
```

It might make sense to have both versions for different kinds of commands. What do you think? Could you give me an example of the kind of switch you'd need this for so I can think through the use cases?

**Comment by unphased** [comment]
This would be insanely powerful and open a lot of doors!

**Comment by amerlyq** [comment]
Hm. Personally I would better allow lambdas to be used in definition directly.
With captured args from regex passed as arguments. 
E.g. convert timestamp into date
```
let g:switch_custom_definitions = [
      \   {
      \     '\v(\d{10}) ' :     {ts -> system("date +%Y%m%d_%H%M%S -d@".ts)}
      \   }
      \ ]
```
@AndrewRadev , what do you think?

**Comment by AndrewRadev** [comment]
@amerlyq This is not a bad idea, although I did need to resort to some tricks to pull it off. Theoretically, this means that it would be relatively easy to implement system calls on top of that with some more convenience. Here's a set of examples that I've gotten to work:

``` vim
function Base64Decode(input)
  " skip initial base64
  let input = substitute(a:input, ';base64,', '', '')

  let result = system('base64 -d -', input)
  if v:shell_error
    echoerr result
    return a:input
  endif

  return ','.result
endfunction

function Base64Encode(input)
  " skip initial comma
  let input = a:input[1:]
  let result = trim(system('base64 -', input))

  if v:shell_error
    echoerr result
    return a:input
  endif

  return ';base64,'.result
endfunction

let g:switch_custom_definitions = [
      \   {
      \     'data:text/plain\zs,.*':        function('Base64Encode'),
      \     'data:text/plain\zs;base64,.*': function('Base64Decode'),
      \   },
      \   {
      \     '\v(\d{10}) ' : {ts -> trim(system("date +%Y%m%d_%H%M%S -d@".ts)).' '}
      \   }
      \]

" 1632043634 foobar

" data:text/plain,abcdef
```

As you can see, there's more to be done than just `system`, because external commands usually return an empty newline, so a `trim(` is a good idea. There's also the question of, what if there's an error? In your example, I've stuck to a lambda, but I've also passed along a full function with error checking. Maybe I could extract a helper to do this stuff, but for now, what do you think? Can you think of potential issues?

I've pushed this to a branch called [execute-functions](https://github.com/AndrewRadev/switch.vim/tree/execute-functions), so I'd appreciate if you tried it out.

@sevensidedmarble, @unphased What do you think of this kind of interface? It's a bit verbose and might be overwhelming to somebody not that comfortable with Vimscript. But I could package it up in helper functions, as long as I had some examples of the kind of things you'd be interested in doing with it.

**Comment by amerlyq** [comment]
> I've pushed this to a branch called execute-functions, so I'd appreciate if you tried it out.

Cool, it works! Now I can analyze timestamped logs more easily :)

> only works with the full match, but there's no way to pass along individual submatches

Hm, are you sure?)
We have matchlist() and could do something akin:
```vim
call(lambda, matchlist(line, rgx))
```

I suppose you currently passing only group(0) (i.e. whole match), therefore I can't do reverse operation like:
```vim
" NOTE: skip first arg, as we don't need whole match
      '\v<(20\d\d)(\d\d)(\d\d)_(\d\d)(\d\d)(\d\d)>' : {_,y,m,d,H,M,S -> trim(system("date +%s -d".y."-".m."-".d."T".H.":".M.":".S))}
```

> v:shell_error
> Maybe I could extract a helper to do this stuff

Not sure why we must especially bother for that on the plugin side, instead of doing error-checking on user side (custom funcs).
If shell fails sometimes -- it's no problem to show default errors (exceptions) to user, as he will ignore them anyway. Let him be aware at least. There is always "undo" if current line becomes messed up due to stderr.
If shell fails all the time -- let user solve exceptions himself by try-catch in function and doing his work properly.
And if user don't understand where this error comes from -- there is always ":debug" and "nvim -V20log".

P.S. I'm still confused by what these mime types mean and how are they supposed to be used:
```vim
      \     'data:text/plain\zs,.*':        function('Base64Encode'),
      \     'data:text/plain\zs;base64,.*': function('Base64Decode'),
```
I couldn't find any relation to data schema in source code.
Moreover, I suppose @sevensidedmarble wanted to convert base64 pieces scattered in some json/etc, therefore there is even less purpose of having mime attached to switch. So, @AndrewRadev, what is the supposed usecase for that?

**Comment by AndrewRadev** [comment]
>  We have matchlist() and could do something akin:

Not exactly, not in the way the plugin works right now -- the way that is implemented, it uses a `:substitute` call, and the lambda/function invocation is a bit of a hack: https://github.com/AndrewRadev/switch.vim/blob/468dfa3c46ff27d650cfd708cf3313e08b708e31/autoload/switch/mapping.vim#L128-L134

There's also the problem that lambdas just ignore extra arguments, explicit function calls don't. If you have an older Vim, you won't have lambdas. Or, if you would just like to write down more code, it would make sense to just pass a function along, but you wouldn't be able to.

Even if I were to move to `substitute(` of strings with direct replacement of the contents, this doesn't quite solve the problem, and it removes the ability to use some patterns like cursor position, visual mode or mark. I don't actually think they're super useful, but as I said, it doesn't actually solve the above problem with function arguments.

What I've done now is passed along all the submatches in an array, so you'd have to access the 0-th element to get the full match. Something like:

```
\     '\v(\d{10}) ' : {m -> trim(system("date +%Y%m%d_%H%M%S -d@".m[0])).' '}
```

It's a bit clumsier, but since it's just one argument, it'll work with both functions and lambdas.

> Not sure why we must especially bother for that on the plugin side, instead of doing error-checking on user side (custom funcs). 

I wouldn't say I *must* do it :). I would just prefer that people can customize the plugin easily and with limited knowledge of vimscript. One benefit of the language is that you really don't need to know a lot of it to just customize plugins. You don't need to know what the syntax of a lambda is, for example, especially since it's kind of different to any other language in small ways. And even if I did add it, nothing's stopping you in particular from using a lambda.

> If shell fails sometimes -- it's no problem to show default errors (exceptions) to user, as he will ignore them anyway

If you execute `:call system('foobar')`, you won't get any error, it'll fail silently. If you execute `:echo system('foobar')`, you'll see the error message, and it won't be shown, but instead it'll get replaced in the buffer, which could be a surprise. It's not a big problem, you can always undo, it just doesn't seem like good user experience to me. For plugins that I personally use, I prefer them to have sensible UX. I'm often annoyed for example that some plugin throws big errors in the beginning if I don't happen to have python3 installed -- Maybe I just can't do anything about that right now, I'm on a machine that doesn't have it compiled, etc. I don't want to have to pause every time I launch a new Vim to press enter to remove a warning I can do nothing about. I try to be better than this.

>  Moreover, I suppose @sevensidedmarble wanted to convert base64 pieces scattered in some json/etc, therefore there is even less purpose of having mime attached to switch. So, @AndrewRadev, what is the supposed usecase for that?

I don't know what the use case is, that's why I asked :). If you want to replace some strings scattered in json, it's likely better to just select them in visual mode and apply an external command, or maybe use `substitute`. This plugin's idea is to have some kind of pattern that you can match and operate on in a consistent way -- I didn't get an example of a pattern like this. The example I gave came from base64-encoded HTML -- I don't personally care about it, but I don't have any better example to point to. Your datetime example is useful, and I'm just using the other one to demonstrate how you might use functions instead of lambdas.

**Comment by amerlyq** [comment]
> It's a bit clumsier, but since it's just one argument, it'll work with both functions and lambdas.

Nice, `m[0]` will do the task fine too.
I understood why you don't want to unpack arguments yet ;)

> customize the plugin easily and with limited knowledge of vimscript

Knowledge of lambda passing based on capture groups of regex and system call inside... I wouldn't say this knowledge is totally basic, so current feature is targeting more powerful users, but maybe there will be cases of people which know all of that and still don't know of v:error, etc. Hmm... wouldn't they copycat some other dudes vim configs in that case ? :D

> plugin throws big errors in the beginning

Yeah, they are annoyingly irritating, I can relate.
Can't vote for processing v:error by "reasonable defaults", but providing optional wrapper for lambdas, focused around system calls may be beneficial. Still it may be not worth the efforts if there is no demand -- as I mentioned earlier, this feature most probably targets more powerful users.

> The example I gave came from base64-encoded HTML

Aaah! That's it, so `data:text/plain\zs,.*` is the text directly present in buffer.
I thought that everything before comma is some kind of magical gimmics with internal logic attached to mime :)
I'm reassured now.

**Comment by AndrewRadev** [comment]
> Still it may be not worth the efforts if there is no demand -- as I mentioned earlier, this feature most probably targets more powerful users.

Yes, being able to pass along a function reference is something that just opens up the door for anybody to do what they want, and in that case, you do need to know Vimscript. I would say that if I just made a function that does `'\v(\d{10}) ' : switch#SystemCall("date +%Y%m%d_%H%M%S -d@\0")` allows people to execute external commands without caring about lambdas, or `v:error`, or anything else other than "I know what a function call looks like". I still don't know if I'll do it, I'll give it a think.

**Comment by AndrewRadev** [comment]
I've merged the branch, so it should be possible to use this functionality normally now -- let me know if you run into any problems. I decided not to add any convenience functions, but we'll see if there's any feedback in the future. For now, I'll close this issue.
